services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/app/config
    working_dir: /app
    secrets:
      - diakhatepalme_com_key
      - diakhatepalme_com_cert
      - diakhatepalme_com_ca_bundle
      - ardenpalme_com_key
      - ardenpalme_com_cert
      - ardenpalme_com_ca_bundle
      - ardendiak_com_key
      - ardendiak_com_cert
      - ardendiak_com_ca_bundle
  
secrets:
  diakhatepalme_com_key:
    file: /etc/pki/tls/private/diakhatepalme_com.key
  diakhatepalme_com_cert:
    file: /etc/pki/tls/private/diakhatepalme_com.crt
  diakhatepalme_com_ca_bundle:
    file: /etc/pki/tls/private/diakhatepalme_com_ca_bundle.crt
  
  ardenpalme_com_key:
    file: /etc/pki/tls/private/ardenpalme_com.key
  ardenpalme_com_cert:
    file: /etc/pki/tls/private/ardenpalme_com.crt
  ardenpalme_com_ca_bundle:
    file: /etc/pki/tls/private/ardenpalme_com_ca_bundle.crt

  ardendiak_com_key:
    file: /etc/pki/tls/private/ardendiak_com.key
  ardendiak_com_cert:
    file: /etc/pki/tls/private/ardendiak_com.crt
  ardendiak_com_ca_bundle:
    file: /etc/pki/tls/private/ardendiak_com_ca_bundle.crt
